server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

aliyun:
  vod:
    keyid: LTAI4G8QYorbFAwpaMXFc4TR
    keysecret: jqHbFc72jJHCJxawXvynbYvUG53hMo
#    templateGroupId:
#    workflowId:

