server:
  port: 8170
  tomcat:
    max-threads: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  profiles:
    active: dev
  application:
    name: service-trade
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8719 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.128:3306/20201219_guli_trade?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: ysf
    password: 132523
    hikari:
      idle-timeout: 30000
      max-lifetime: 55000
      connection-timeout: 30000
      maximum-pool-size: 20
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#redis配置
  redis:
    host: 192.168.1.128
    port: 6379
    database: 0
    password: 132523
    lettuce:
      pool:
        max-active: 20 #最大连接数，负数没有限制
        max-wait: -1 #最大阻塞等待时间，负数表示没限制，默认-1
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
    timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com\stitch\service\edu\mapper\xml\*.xml
#ribbon 负载均衡策略
#service-oss:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略
feign:
  sentinel:
    enabled: true
ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒


weixin:
  pay:
    #关联的公众号appid
    appId: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notifyUrl: http://stitch.free.idcfengye.com/api/trade/weixin-pay/callback/notify
