server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyid: LTAI4G8QYorbFAwpaMXFc4TR
    keysecret: jqHbFc72jJHCJxawXvynbYvUG53hMo
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: file-20201228-1